### ISSUE TITLE
Ridiculously high baud rate is ridiculously high.

### ISSUE THREAD

**Issue by trickeydan** [j5api/sr-motor-v4-fw#1]
Something like 9600 would be much much better.

**Comment by RealOrangeOne** [comment]
In my experience, 9600 is far too slow for anything like this, and has noticeable latency.

The SourceBots servo assemby uses 115200, which is a much better fit https://github.com/sourcebots/servo-firmware/blob/master/src/firmware.cpp#L317

**Comment by trickeydan** [comment]
Bear in mind that each command for this board is only 4 bytes long...

**Comment by RealOrangeOne** [comment]
Then we can make it go super fast!

![](https://i.kinja-img.com/gawker-media/image/upload/s--vxaxX6YM--/c_scale,f_auto,fl_progressive,q_80,w_800/18n2u2jtl147mjpg.jpg)

**Comment by trickeydan** [comment]
According to @prophile, this causes issues with interfacing with the motor board on Mac.

**Comment by kierdavis** [comment]
> this causes issues

What causes issues? The current baud rate, or the proposed fix of changing it to a different value?

**Comment by RealOrangeOne** [comment]
Also, what is 'this'? Increasing the baud rate, having a baud rate of 115200, having a baud rate of 9600? If a mac can't interface at either of those rates, i'd be _very_ surprised, especially considering it's currently higher than both of those

**Comment by trickeydan** [comment]
> > this causes issues
> 
> What causes issues? The current baud rate, or the proposed fix of changing it to a different value?

The current baud of 10^6

> Also, what is 'this'? Increasing the baud rate, having a baud rate of 115200, having a baud rate of 9600? If a mac can't interface at either of those rates, i'd be _very_ surprised, especially considering it's currently higher than both of those

See above

**Comment by trickeydan** [comment]
When we change this, we will need to be able to tell the new baud rate / fw version from the USB descriptors, so that we don't open it at the old baud rate.

**Comment by kierdavis** [comment]
Raised upstream at https://github.com/srobo/motor-v4-fw/issues/7.
